print("Hello from Jenkins! Keep learning! :) ")
print("Hello from Jenkins!, if you can see this, then consider webhook working fine")
print("installed ngrok to make connection from localhost to github to jenkins")
print("csrf issue issue resolved")
print("error 404 resolved")